"""
This script is to be called inside a grasshopper environment to export all the neccessary input for the motion planning. It performs the following tasks:
1. Deletes all files in the collision meshes temp directory.
2. Exports collision meshes to a specified directory.
3. Exports collision meshes in OBJ format.
4. Saves robot metadata and solutions to JSON files.

Inputs:
    robot: The robot object.
    solutions: List of solutions generated by the Inverse Kinematics algorithm.
    metadata_in: JSON string containing metadata.
    collision_obj: Collision objects to export.

"""
import os
import json
import time
import research_project.utilities.grassopper_io.export_mesh as export_Mesh
import research_project.utilities.utils as utils

data_path = utils.get_data_path()
logger = utils.Logger(data_path)

# Export collision meshes
collision_path = os.path.join(data_path, "auto_generated/collision_temp/")
# Delete all files in the folder
for file in os.listdir(collision_path):
    os.remove(os.path.join(collision_path, file))
export_Mesh.MeshExport(collision_obj, collision_path, "OBJ")  # noqa: F821

# Save solutions in json file

timestamp = time.strftime("%y%m%d_%H%M%S")

try:
    metadata_dict = json.loads(metadata_in)  # noqa: F821
except Exception:
    metadata_dict = {}

metadata_dict["robot_spawnpoint"] = [robot.RCF.point.x, robot.RCF.point.y, robot.RCF.point.z]  # noqa: F821
metadata_dict["lift_height"] = robot.lift_height  # noqa: F821

if "planes" in metadata_dict:
    planes = metadata_dict["planes"]
    metadata_dict.pop("planes", None)
    planes_filename = os.path.join(data_path, f"auto_generated/export/{timestamp}_planes.json")
    with open(planes_filename, "w") as f:
        json.dump(planes, f)


metadata_filename = os.path.join(data_path, f"auto_generated/export/{timestamp}_metadata.json")
with open(metadata_filename, "w") as f:
    json.dump(metadata_dict, f)

solutions_filename = os.path.join(data_path, f"auto_generated/export/{timestamp}_solutions.json")
with open(solutions_filename, "w") as f:
    json.dump(solutions, f)  # noqa: F821

logger.log(f"Data exported to: {metadata_filename} and {solutions_filename}")
logger.log("metadata: " + str(metadata_dict))
time_out = time.time()
